### ISSUE TITLE
Temporary deactivate integration

### ISSUE THREAD

**Issue by MiG-41** [Kajkac/ZTE-MC-Home-assistant-repo#10]
When integration works on default settings , changing to "normal web" is very annoing becouse of constant logouts. You have to be very fast ,but sometimes i can't manage i.e. to select all Bands and Set them.... Even when default value is 100s ,this logouts are much faster....
Stop integration works , but disabling it manualy takes also some time ... Perhaps it is somehow possible to have switch for it ?
How to change default values ( time , password ), by editing file ?

**Comment by Kajkac** [comment]
I will try to pull initial configuration in the configure menu of integration so that refresh time can be changed. Stopping the integration by switch isnt kind a right way, i can only try to add some kind of service mode switch which can temoprary stop refreshing of data. This router firmwares dont have multiple user mode or api so that integration cannot work without logging out user who is tryin to log in to web interface.

**Comment by MiG-41** [comment]
Looks like integration reads data every 30s. Perhaps that is to often ? 1 min should be sufficent.

**Comment by Kajkac** [comment]
Delete integration and re add it and put time for data fetch and sms higher

**Comment by Kajkac** [comment]
I release a new build with timer treshold fix, and configure functionality on integration, test it when you can.

**Comment by MiG-41** [comment]
I put new ping value to 200s ( i removed completly integration first) , and it started updating "Monthly Time" something like 3min 30s , so seems this is fixed now.
Also button for Configuration apear now ,however it is not possible to put there new values. Tried to change this to 60 , to 100 , it says that it is saved succesfully , however nothing really changed, when you go once again for configuration there is previous 200 all the time. Restarting HA also don't help , cleaning cache of browser as well...

**Comment by Kajkac** [comment]
Oh dam, i will check it maybe i forgot to populate configuration entry to make succesfull save :)

**Comment by Kajkac** [comment]
Now it should be ok.

**Comment by MiG-41** [comment]
Not really :)
In v1.0.20 konfiguration is updating/chaanging , but integration use permanently initial datas , don't care about new values....
Initially set to 60s and that was the time of update entity "Monthly Time" , no matter if in configuration i changed Ping Interval to 30s or to 300s. I also restarted HA , real time of reading still is 60s.

**Comment by Kajkac** [comment]
I have tested this on my two routers and time treshold now is working fine so closing the issue

**Comment by Kajkac** [comment]
Did you remove integration and add it again ? I have done it a lot of times trough hacs and manualy and all is working for me, changing config etc…

**Comment by MiG-41** [comment]
Is Reconfiguration at your side works in a way , that integration uses new ping times ?

**Comment by Kajkac** [comment]
I will try to test that today and i will let you know, i did put higher times 300for sensors and 350 for sms and that is working fine.

**Comment by MiG-41** [comment]
Did you veryfied it ?
I tested on version 1.0.23 ,and same story , reconfigured time is not considered ,only initialPing time. I can set also higher values , and nothing changes...
