### ISSUE TITLE
The repo is not working on my HA

### ISSUE THREAD

**Issue by Andrege16100** [Kajkac/ZTE-MC-Home-assistant-repo#11]
Hi! I have a ZTE Mc801A.
I've installed your repo following your instructions but I received alsways the same error:
![image](https://github.com/user-attachments/assets/cb9147f1-90cf-42c2-9cb1-7cb0e2f2c829)
![image](https://github.com/user-attachments/assets/af930e69-1ec5-4b81-80f4-6f20f0ddd693)

What could be my mistake?
Maybe I've to enable something like remote managment on the router?

Thanks in advance: I'm a new user of HA and I have to learn a lot of things..

**Comment by Andrege16100** [comment]
Thanks for your reply.
Before writing here I've tried several times to remove and reinstall the repo (also the oldest, the unsupported) without differenti results.
I'm sure that the address and the password are correct because they work on the browser.
I have only to try to insert the repo manually but i have still to understand how. ;)
I Will look for some tutorial.
Thanks anyway for your help!

**Comment by MiG-41** [comment]
The easiest way is to install Samba in HA , then you have acces to the files via network drives: https://smarthomecircle.com/easily-share-files-with-home-assistant-using-samba-share

**Comment by Shariner** [comment]
> The easiest way is to install Samba in HA , then you have acces to the files via network drives: https://smarthomecircle.com/easily-share-files-with-home-assistant-using-samba-share
> 
> @Kajkac , HACS is downloading this integration to catalog '/config/custom_components/zte_tracker' instead '/config/custom_components/zte_router' ( confirmed by doing this) ,could be a reason why it is having issues ? ![image](https://private-user-images.githubusercontent.com/57936100/358636411-724d9158-83f2-4986-b943-c439d329578c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjQ2ODQsIm5iZiI6MTcyMzgyNDM4NCwicGF0aCI6Ii81NzkzNjEwMC8zNTg2MzY0MTEtNzI0ZDkxNTgtODNmMi00OTg2LWI5NDMtYzQzOWQzMjk1NzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE2MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NzI5MTkzMWMzODIxZmFiYmU3MTA5ZWY0NTBlNDEwNjEyNDg2NDU0MDI0OGQwZDU5ZGM3MjRlODliMDFmOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UA25FArG18zRwfx-umCyvyJdQH1_EBOXTD0pTKjLpek)
> 
> Could be this commit from @Shariner [6736049](https://github.com/Kajkac/ZTE-MC-Home-assistant-repo/commit/6736049fa74b01b6112c0a80a3dd34c8fa5cb2c9)

I had the same experience when i tried installing via HACS on my own branch, then i edited the linked commit in my own branch and it was working, so yes this is the reason, it expexts the domain zte_tracker.

You could simply rename the folder for a quick fix. I don't think my pull request will be merged as it's now not compatible anymore, so someone needs to adjust it and open another pull request or fix it by hand.

**Comment by Kajkac** [comment]
Yeah i know, will push the next update with more fixes as soon as i can, for now manual installation works fine

**Comment by Andrege16100** [comment]
I followed your instructions for manual installation and now the repo works without problem!
Thanks for your time and your help! I appreciate!

**Comment by MiG-41** [comment]
In meantime there was update HACS from 1.x to 2.0. Yesterday i got notification , that ZTE_router can be upgraded to 1.0.21 ( from 1.0.20). So i did it , and after that there where several errors . So i updated manually , added once again integration ,and this works.
So either 1.0.21 has improved this errors and there won't be them during HACS update , or there is still something wrong...

**Comment by Kajkac** [comment]
The router domain is fixed, hacs repositroy merge is pending but manual repository and manual istallation is working so closing the issue
