### ISSUE TITLE
At integration loading (restart HA) the integration sometimes pulls 0.0 for rx_bytes sensors (and corresponding data_usage sensors)

### ISSUE THREAD

**Issue by Shariner** [Kajkac/ZTE-MC-Home-assistant-repo#7]
At integration loading (e.g. restart HA) the integration sometimes pulls 0.0 for rx_bytes sensors (and corresponding data_usage sensors)

This issue is addressed in the next pull request. 

To fix these statistic data issues for the past you have to repair the database.

For example mariadb:

```
UPDATE states
SET state = 'unavailable'
WHERE state = '0.0'
  AND metadata_id IN (
    SELECT metadata_id
    FROM states_meta
    WHERE entity_id IN ('sensor.monthly_rx_gb', 'sensor.monthly_tx_gb', 'sensor.monthly_usage')
  );
```

SQL command tested.

**Comment by Shariner** [comment]
Ah: After the next pull request, the data_left integration will not having these spikes to the set up data contigent anymore, but you also need to fix the database, just change the corresponding sql command. You can work this out for yourself, you just need to set all values to unavailable which have your "max data" value. at my case: 200GB

**Comment by MiG-41** [comment]
This is probably general problem with connection or read data , since all sensors are not updated sometimes.
Here is examples from 4 entities from 1h , black spaces means that it was no data read:
![image](https://github.com/user-attachments/assets/787b4a5a-b17e-4731-b160-f1c1afb43aa8)

**Comment by Shariner** [comment]
> This is probably general problem with connection or read data , since all sensors are not updated sometimes. Here is examples from 4 entities from 1h , black spaces means that it was no data read ,and it correspond to 0.0 read from i.e. Monthly TX GB:
> 
> ![image](https://private-user-images.githubusercontent.com/57936100/357503729-3d86085a-b5ba-49c2-94c0-640ae9137525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Nzc5MTksIm5iZiI6MTcyMzU3NzYxOSwicGF0aCI6Ii81NzkzNjEwMC8zNTc1MDM3MjktM2Q4NjA4NWEtYjViYS00OWMyLTk0YzAtNjQwYWU5MTM3NTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE5MzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YjY0NzJiZjM4NDcwNTY3MGQ4NGI3NzM5MjM1MGY3MzJjZDRkMjA4YzVhM2VhMWUzN2VjMDgzOTY0MTU5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CCf9tFGjSpVmhJe36HODed3MllQTUagjlKyHbT5FWBo)
> 
> So it should be some verification/ reapeated read or whatever ,before updating entities , instead @Shariner is making some workorounds for onlt few entities....

Everyone can participate in this project, feel free.

**Comment by Kajkac** [comment]
I will look at it, i did some fixes before for this part and its mainly coz sometimes script dont get data or python comand to get data failed(its not perfect solution) but thats on zte coz it doesnt have proper api, so need to see how to preserve state and not read 0, currently i am litle busy at work so i didnt have time to look at it, but i will try to implement some workarounds on integration itself

**Comment by Kajkac** [comment]
I push out new release which includes retry for getting the sensor data, in my debug logs i see often that on restart or sometimes script failed to get data, so i implement 3 times retry, i hope this can solve intermitent data on sensors. I will leave it for today to see if sensors get any 0.00 data.

**Comment by MiG-41** [comment]
Still noticing "gaps"
![image](https://github.com/user-attachments/assets/77aa12ed-b2b2-4aa1-a2b2-56d9bc02826d)

**Comment by MiG-41** [comment]
On 1.0.17 similar , random gaps:
![image](https://github.com/user-attachments/assets/f9d127a9-dbd1-4e96-a3ef-5bf276ce6f33)

**Comment by Kajkac** [comment]
Can you try with version 18, i think situation is much better at least on my router

**Comment by MiG-41** [comment]
Yes , now it is ok.

**Comment by MiG-41** [comment]
We have to go back to this issue again... Becouse now ,even router will be disconnected , integration not show it. 
Yesterday one of my routers was accidently powered off for some hours, but HA didn't show any problems ( like unavailble) , and after powered up again old values where till that time , and new updated ( not showing gap unavailble  beetween them...)

**Comment by MiG-41** [comment]
Same here, from 2 days device is disconnected , but in HA frozen values:
![image](https://github.com/user-attachments/assets/f1ea2513-faad-4568-b2e7-052297a94191)

It is needed to be "unknown" or something like this instead...
